### ISSUE TITLE
Credit where credit's due

### ISSUE THREAD

**Issue by delgadom** [GClunies/py_noaa#17]
As this is turning into a proper package, it deserves some badges. These can be added to the readme to signify build status, pypi distribution, and other features.

Usually, these are added to the very top of the readme, all on one line (e.g. see https://github.com/pydata/xarray)

### travis build status
[![Build Status](https://travis-ci.org/GClunies/py_noaa.svg?branch=master)](https://travis-ci.org/GClunies/py_noaa)
```[![Build Status](https://travis-ci.org/GClunies/py_noaa.svg?branch=master)](https://travis-ci.org/GClunies/py_noaa)```

### pypi version
[![PyPI](https://img.shields.io/pypi/v/py_noaa.svg)](https://pypi.python.org/pypi/py-noaa)
```[![PyPI](https://img.shields.io/pypi/v/py_noaa.svg)](https://pypi.python.org/pypi/py-noaa)```

### python versions
[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/py_noaa.svg)](https://pypi.python.org/pypi/py-noaa)
```[![PyPI - Python Version](https://img.shields.io/pypi/pyversions/py_noaa.svg)](https://pypi.python.org/pypi/py-noaa)```

### other services
* test coverage: [coveralls.io](https://coveralls.io)
* code quality: [codacy.com](https://codacy.com)

there's tons of other stuff, but these are some of the ones I regularly use.

### other badges
http://shields.io/

**Comment by GClunies** [comment]
Sorry for the late response @delgadom , and thanks for the suggestion. Will add these in shortly.

**Comment by GClunies** [comment]
When I said "shortly"... i meant I will forget about this and it will take forever.

**Comment by delgadom** [comment]
looks great :)
