### ISSUE TITLE
for parameter "hourly_height," concatenating subsequent years duplicates data from the first day in the defined series

### ISSUE THREAD

**Issue by CraigHarter** [GClunies/py_noaa#35]
If I submit the following command:

df = coops.get_data(
        begin_date='20070101',
        end_date='20090101',
        stationid='8737048',
        product='hourly_height',
        datum='msl',
        units='english',
        time_zone='lst'
        )

then the day of 2008-01-01 will be duplicated in the resulting dataframe. This is because the first API batch call is for a one year period (ending on 2008-01-01) and the subsequent batch call will begin on 2008-01-01. Thus that date is duplicated in the resulting time series.

**Comment by GClunies** [comment]
Good catch. 

This may be as simple as using Pandas .drop_duplicates() method before return the final DataFrame to end user.

**Comment by CraigHarter** [comment]
That's what I did to the final results. Worked fine.

**Comment by GClunies** [comment]
This is being addressed in new [noaa_coops](https://github.com/GClunies/noaa_coops) package.
